ball_handler:
 boh_rot_speed: 200
 boh_autorot_speed: 150
 boh_random_speed_stop_min: 100 # both min and max have to be positive
 boh_random_speed_stop_max: 200
 boh_random_speed_move_min: 100 # both min and max have to be positive
 boh_random_speed_move_max: 200
 boh_speed_change_period: 1.0

arm:
 up_speed: 200 #CCR
 down_speed: -255 #CCR
 homing_speed: 170 #CCR
 max_limit: 400 #[mm]
#  min_limit: 50 #[mm]
 max_limit_ex: 160 #[mm]
movable_rail:
 up_speed: -180 #CCR
 down_speed: 200 #CCR
 homing_speed: 150 #CCR
 max_limit: 200 #[mm]
 min_limit: 40 #[mm]
others:
 sleep_t_after_catch: 0.5 # 0.5 #[s]
 sleep_t_after_release: 1.5 #[s]

omni:
 #手動走行なら、max_linear_velの値は2.0m/sくらいが良い
 max_linear_vel_fast: 2.5 #unit: m/s
 max_rotation_vel_fast: 2.5 #unit: rad/s
 max_linear_vel_slow: 1.3 #unit: m/s     original -> 1.5
 max_rotation_vel_slow: 1.8 #unit: rad/s original -> 2.0
